---
title: "HockeyDFS.rmd"
output: html_document
date: "2022-12-19"
---


### Setup
```{r setup, include= FALSE}
library(lpSolve)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(coach)
library(googlesheets4)
library(R.utils)
library(tm)
options(dplyr.summarise.inform = FALSE)

```



### My optimizer
```{r lpSolve-opto}
# Parameters
 
# stacks may need to be full info from all_lines for creating the vectors

  num_lineups <- 20
  stack1size <- 4
  stack2size <- 3
  testing <- F
  variance <- 50 # increase here increases lineup diversity with regards to stack selection; check times_stacked to ensure appropriate diversity
  darts <- 3 # projection cutoff for dart throw players; also affects which D can be included in stacks
  num_darts <- 1 # max players below 'darts' projection allowed
  min_own <- 0.3 # combined min own threshold - if ownership is available, probably consider needing some chalk; otherwise set to 0
  pp_factor <- -.8 # increase here increases odds of getting a PP line as a stack; likely better for larger slates
  need_value <- 2.5 # affects how much stack price impacts selection
  min_salary <- 48500
  
  timeout_threshhold <- 0.3
  bans <- NULL #
  pb <- txtProgressBar(0, num_lineups, style = 3)
  
if(!testing){
data <- read_dk("C:/Users/jorda/Downloads/DKSalariesNHL.csv")
projections <- read_sheet("https://docs.google.com/spreadsheets/d/1ktMclwMSxcjW3WIHOdMhnNpzWcmO6gPqKdtLaAHN2nQ/edit#gid=1735928548")


  # Building dataframe


  
  data <- select(data, player_id, player, salary, opp_team)
  projections <- select(projections, Name, DK.Implied.FPs, Position, Team, Line, PP.Line.1, DKOwnProj) %>%
    rename(player = Name, fpts_proj = DK.Implied.FPs) 
  
   data <- merge(data, projections)
   teams <- data$Team %>%
    unique()

   odata <- data
}
  times_stacked <- data.frame(stack_name = c(gsub(" ", "", paste0(teams, "1")), gsub(" ", "", paste0(teams, "2")), gsub(" ", "", paste0(teams, "3")),gsub(" ", "", paste0(teams, "4")),gsub(" ", "", paste0(teams, "PP"))), stacked = 0)
  
timeouts <- 0
rm(lineups)
t <- 0
while(t < num_lineups){
  timeouts <- timeouts+1
  
  tryCatch(expr = {withTimeout({
  
  data <- odata %>%
    filter(!(player == "Sebastian Aho" & salary <= 3500)) %>%
    filter(!player %in% bans) %>%
    distinct()

      first_line <- data %>%
      filter(Line == 1) %>%
      group_by(Team) %>%
      summarise(line_proj = max(fpts_proj), cost = max(salary)) %>%
      mutate(stack = gsub(" ", "", paste(Team, "1")))
      second_line <- data %>%
      filter(Line == 2) %>%
      group_by(Team) %>%
      summarise(line_proj = max(fpts_proj), cost = max(salary)) %>%
      mutate(stack = gsub(" ", "", paste(Team, "2")))
      third_line <- data %>%
      filter(Line == 3) %>%
      group_by(Team) %>%
      summarise(line_proj = max(fpts_proj), cost = sum(salary)) %>%
      mutate(stack = gsub(" ", "", paste(Team, "3")))
      fourth_line <- data %>%
      filter(Line == 4) %>%
      group_by(Team) %>%
      summarise(line_proj = max(fpts_proj), cost = sum(salary)) %>%
      mutate(stack = gsub(" ", "", paste(Team, "4")))
      pp_line <- data %>%
      filter(PP.Line.1 == TRUE) %>%
      group_by(Team) %>%
      summarise(line_proj = max(fpts_proj)*pp_factor, cost = max(salary)) %>%
      mutate(stack = gsub(" ", "", paste(Team, "PP")))
      
      all_lines <- rbind(first_line, second_line, pp_line, third_line, fourth_line)
      all_lines$line_proj <- rnorm(nrow(all_lines), sqrt(all_lines$line_proj+sqrt(all_lines$cost)), 5)
      all_lines$line_proj[all_lines$line_proj < 0] <- 0
      all_lines <- all_lines %>%
        group_by(Team) %>%
        slice_max(line_proj) %>%
        ungroup()
      stacks <- all_lines[sample(seq_len(nrow(all_lines)), 2, prob = all_lines$line_proj),]
    
      data<- data %>%
        mutate(stackline = case_when(
          (gsub(" ", "", paste0(Team, Line)) == stacks$stack[1] & (Position %in% c("C", "W") | ((Position == "D") & fpts_proj > darts)))| gsub(" ", "", paste0(Team, "PP")) == stacks$stack[1]~ "stack1",
          (gsub(" ", "", paste0(Team, Line)) == stacks$stack[2] & (Position %in% c("C", "W") | ((Position == "D") & fpts_proj > darts)))| gsub(" ", "", paste0(Team, "PP")) == stacks$stack[2] ~ "stack2",
          Position %in% c("G") & opp_team %in% stacks$Team ~ "opp_g",
          Position %in% c("G") ~ "G",
          Team %in% stacks$Team ~ "ignore",
          T ~ "unstacked"
        ), fpts_proj = case_when(fpts_proj <0 ~ 0, T ~ fpts_proj))
    
  
### my optimizer


  
## Objective
data$fpts_proj[is.na(data$fpts_proj)] <- 0
data$fpts_proj[is.nan(data$fpts_proj)] <- 0
data$fpts_proj[is.infinite(data$fpts_proj)] <- 0
objective.in <- rnorm(length(data$fpts_proj), data$fpts_proj, sd = 2+data$fpts_proj/4)

## Constraint matrix - salary, is in a stack, position, util


vsalary <- data$salary
vcenter <- as.numeric(data$Position == "C")
vwing <- as.numeric(data$Position == "W")
vdef <- as.numeric(data$Position == "D")
vgoal <- as.numeric(data$Position == "G")
vutil <- as.numeric(!vgoal)
vplaying <- as.numeric(data$fpts_proj > 0)
vdarts <- as.numeric(data$fpts_proj <= darts & data$stackline  == "unstacked" & !data$Position == "G")
vstack1 <- as.numeric(data$stackline == "stack1")
vstack2 <- as.numeric(data$stackline == "stack2")
voneoff <- as.numeric(data$stackline == "unstacked")
voppg <- as.numeric(data$stackline == "opp_g")
vown <- data$DKOwnProj

matrix_vector <- c(vsalary, vsalary, vcenter, vwing, vdef, vgoal, vutil, vplaying,  vdarts, vstack1,vstack2,  voneoff, voppg, vown)

  
matrix_vector[is.na(matrix_vector)] <- 0
matrix_vector[is.infinite(matrix_vector)] <- 0

const.mat = matrix(matrix_vector, nrow = length(matrix_vector)/length(data$salary), byrow = TRUE)

## Define constraints and direction - 50000 salary
const.rhs = c(50000, min_salary,  2,  3,  2,   1,    8,    9, num_darts, stack1size, stack2size, 1, 0, min_own)
const.dir = c("<=", ">=",">=",">=",">=", "==", "==", "==",  "<=", "==","==", ">=", "==", ">=")




### Optimize
objective.in[is.nan(objective.in)] <- 0
objective.in[objective.in < 0] <- 0
optimum = lp(direction = "max", objective.in, const.mat, const.dir, const.rhs, all.bin = TRUE)

data$optimal <- optimum$solution
#if(sum(data$optimal)>0){


l1 <- data %>%
  filter(optimal == 1) %>% 
  select(player_id, Position)

if(length(l1$player_id)>0){

lc <- filter(l1, Position == "C") %>% select(-Position)
lw <-  filter(l1, Position == "W") %>% select(-Position)
ld <-  filter(l1, Position == "D") %>% select(-Position)
lg <-  filter(l1, Position == "G") %>% select(-Position)
u <- case_when(length(lc$player_id)>2 ~ lc$player_id[3], length(lw$player_id)>3 ~ lw$player_id[4], length(ld$player_id)>2 ~ ld$player_id[3])
lc<- filter(lc, !player_id == u)
lw<- filter(lw, !player_id == u)
ld<- filter(ld, !player_id == u)
l1 <- c(lc$player_id, lw$player_id, ld$player_id, lg$player_id, u)


if(t > 0){
 
  lineups <- cbind(lineups, l1)

} else{

  lineups <- as.data.frame(l1)

}
lineups <- lineups %>% unique()
 t <- ncol(lineups)
       times_stacked <- mutate(times_stacked, stacked = case_when(stack_name %in% stacks$stack ~ stacked + 1, T ~ stacked))
 setTxtProgressBar(pb, t)
}
 #}
    
}, timeout = timeout_threshhold)}, TimeoutException = function(ex) {#cat("\nTimeout. Lineups built so far: ", n-1, "/", num_lineups," \n")
  })
  

    
}
close(pb)
times_stacked <- times_stacked[order(times_stacked$stacked, decreasing = TRUE),]

ownership <- data %>%
  select(player, player_id)
ownership$ownership_pct <- 0

for(i in 1:length(ownership$player)){
  ownership$ownership_pct[i] = sum(lineups == ownership$player_id[i])
}
ownership$ownership_pct <- ownership$ownership_pct/ num_lineups*100
ownership <- ownership[order(ownership$ownership_pct, decreasing = TRUE),]

cat("\nBuild fails: ", timeouts-t)

lineups <- t(lineups)
colnames(lineups) <- c("C", "C", "W", "W", "W", "D", "D", "G", "UTIL")

write.csv(lineups, "C:/Users/jorda/Downloads/DKLineupsNHL.csv", row.names = FALSE)
```


### Lineup Editor
```{r lineup-editor}

### Build lineups above, then use this to edit entries for direct upload

plineups <- read.csv("C:/Users/jorda/Downloads/DKEntriesNHL.csv")

plineups <- filter(plineups, !is.na(Entry.ID) & !is.na(as.numeric(Entry.ID))) %>%
  select(Entry.ID, Contest.Name, Contest.ID, Entry.Fee)

newlineups <- read.csv("C:/Users/jorda/Downloads/DKLineupsNHL.csv")

newlineups <- cbind(plineups, newlineups)
colnames(newlineups) <- c("Entry ID", "Contest Name", "Contest ID", "Entry Fee", "C", "C", "W", "W", "W", "D", "D", "G", "UTIL")

write.csv(newlineups, "C:/Users/jorda/Downloads/DKEntriesNHL.csv", row.names = FALSE)

```


### Game Analysis
```{r game-analysis}

sheet_data <- read_sheet("https://docs.google.com/spreadsheets/d/1ktMclwMSxcjW3WIHOdMhnNpzWcmO6gPqKdtLaAHN2nQ/edit#gid=1735928548")

#x <- sheet_data[complete.cases(sheet_data),]
x <- filter(sheet_data, DKOwnProj > 0 & Position == "G" & DK.Implied.FPs > 0 & DK.Implied.FPs != 10)

fp_model <- lm(DK.Implied.FPs ~ `DK Salary` + DKOwnProj, data = x)
summary(fp_model)
```



### Jan 17 optimizer
```{r jan-optimizer}

testing <- F
simplify <- F
stack1size <- 4
stack2size <- 3
num_lineups <- 20
allow_one_skater_against_goalie <- F
core <- c("EDM", "COL")
stacks_in_core <- 0 #set to 0 to let builder do its thing without constraint\
bans <- NULL#c("Justin Barron")
jvalue_min <- 3
min_sum_jvalue <- 30 # combined jvalues for lineup
top_option_jvalue <- 4 # number (count) of plays out of [stack1, stack2, individual, goalie] that must be above top_play_jvalue
top_play_jvalue <- 3.3 # controls jvalue threshold for above
own_cap <- .000

if(!testing){
oprojections <- read_sheet("https://docs.google.com/spreadsheets/d/1ktMclwMSxcjW3WIHOdMhnNpzWcmO6gPqKdtLaAHN2nQ/edit#gid=2082185762") %>%
  filter(!Name %in% bans, !is.na(Name))
}

oprojections <- oprojections %>%
  filter(!Line == "OUT" | is.na(Line == "OUT"), ownership >= own_cap) %>%
  unique()

pb <- txtProgressBar(0, num_lineups, style = 3)


n <- 0
while(n < num_lineups){
if(simplify){
  projections  <- oprojections %>%
    filter(!is.na(Name), Team %in% c("EDM", "SEA", "WAS", "MIN", "WPG", "MON"))
}else{
  projections <- oprojections %>%
    filter(!is.na(Name))
}

projections$build_proj <- rnorm(nrow(projections), mean = projections$DK.Implied.FPs, sd = projections$DK.Implied.FPs/2)
#projections$stackline <- gsub(" ", "", paste0(projections$Team, projections$Line))

projections$top_options_jvalue <- as.numeric(projections$jvalue > top_option_jvalue)

stacked_players <- projections %>%
  filter(Line %in% c("1", "2")) %>%
  mutate(stackline = gsub(" ", "", paste0(Team, Line)))
         
pp_players <- projections %>%
  filter(PP.Line.1) %>%
  mutate(stackline= gsub(" ", "", paste0(Team, "PP")))

teams <- stacked_players %>%
  select(Team, Opp) %>%
  unique()

stacks <- c(gsub(" ", "", paste0(teams, "PP")), gsub(" ", "", paste0(teams, "1")), gsub(" ", "", paste0(teams, "2")))

goalies <- filter(projections, is.na(Line) & DK.Implied.FPs > 0)

stack1 <- stacked_players%>%
  group_by(Team, stackline)%>%
  slice_max(order_by = build_proj, n = stack1size) 

summarise_stack1 <- stack1 %>%
  summarise(build_proj = sum(build_proj),
            `DK Salary` = sum(`DK Salary`),
            ncenter = sum(Position == "C"),
            nwing = sum(Position == "W"),
            ndef = sum(Position == "D"),
            kelly = sum(kelly),
            jvalue = sum(jvalue))

stack2 <- stacked_players%>%
  group_by(Team, stackline)%>%
  slice_max(order_by = build_proj, n = stack2size)

summarise_stack2 <- stack2 %>%
  summarise(build_proj = sum(build_proj), `DK Salary` = sum(`DK Salary`), ncenter = sum(Position == "C"), nwing = sum(Position == "W"), ndef = sum(Position == "D"), kelly = sum(kelly),
            jvalue = sum(jvalue))

stack1pp <- pp_players%>%
  group_by(Team, stackline)%>%
  slice_max(order_by = build_proj, n = stack1size) 

summarise_stack1pp <- stack1pp %>%
  summarise(build_proj = sum(build_proj), `DK Salary` = sum(`DK Salary`), ncenter = sum(Position == "C"), nwing = sum(Position == "W"), ndef = sum(Position == "D"), kelly = sum(kelly),
            jvalue = sum(jvalue))

stack2pp <- pp_players%>%
  group_by(Team, stackline)%>%
  slice_max(order_by = build_proj, n = stack2size)

summarise_stack2pp <- stack2pp %>%
  summarise(build_proj = sum(build_proj), `DK Salary` = sum(`DK Salary`), ncenter = sum(Position == "C"), nwing = sum(Position == "W"), ndef = sum(Position == "D"), kelly = sum(kelly),
            jvalue = sum(jvalue))

summarise_stack1 <- rbind(summarise_stack1, summarise_stack1pp)
summarise_stack2 <- rbind(summarise_stack2, summarise_stack2pp)

summarise_stack1$which_stack <- "stack1"
summarise_stack2$which_stack <- "stack2"

stack_list <- rbind(summarise_stack1, summarise_stack2)

stack_list <- rename(stack_list, Name = stackline)

goalies <- select(goalies, Team, Name, build_proj, `DK Salary`, kelly, jvalue)
goalies$which_stack <- "goalie"
goalies$ncenter <- 0
goalies$nwing <- 0
goalies$ndef <- 0


players <- projections %>%
  filter(! Name %in% goalies$Name) %>%
  select(Team, Name, build_proj, `DK Salary`, Position, kelly, jvalue)
players$which_stack <- "player"
players$ncenter <- players$Position == "C"
players$nwing <- players$Position == "W"
players$ndef <- players$Position == "D"
players <- select(players, -Position)

all_considerations <- rbind(stack_list, goalies, players)
all_considerations <- merge(all_considerations, teams)

vstack1 <- as.numeric(all_considerations$which_stack == "stack1")
vstack2 <- as.numeric(all_considerations$which_stack == "stack2")
vplayer <- as.numeric(all_considerations$which_stack == "player")
vgoal <- as.numeric(all_considerations$which_stack == "goalie")
vcenter <- all_considerations$ncenter
vwing <- all_considerations$nwing
vdef <- all_considerations$ndef
vsalary <- all_considerations$`DK Salary`
vselect_limit <- as.numeric(all_considerations$build_proj > 0)
vskaters <- vcenter + vwing + vdef
vcore <- as.numeric(all_considerations$Team %in% core & all_considerations$which_stack %in% c("stack1", "stack2"))
vjvalue <- as.numeric(all_considerations$jvalue > top_play_jvalue)
vsumjvalue <- as.numeric(all_considerations$jvalue)
vtop_options_jvalue <- all_considerations$top_options_jvalue
vteams <- c()

for(t in 1:nrow(teams)){
  vteam <- as.numeric(all_considerations$Team==teams$Team[t] & all_considerations$which_stack == "player")*2
  vteam_stack <- as.numeric(all_considerations$which_stack %in% c("stack1", "stack2") & all_considerations$Team==teams$Team[t])*4
  vteam_goalie <- as.numeric(all_considerations$which_stack == "goalie" & all_considerations$Team==teams$Team[t])*1
  vopp_goalie <- as.numeric(all_considerations$which_stack == "goalie" & all_considerations$Team==teams$Opp[t])*(3+as.numeric(!allow_one_skater_against_goalie))
  
  vteams <- c(vteams, vteam+vteam_goalie+vteam_stack+vopp_goalie) # should be const.dir "<" and const.rhs "2"; team+goalie will count as 1.5, team+opp g = 2
}


matrix_vector <- c(vsalary, vcenter, vwing, vdef, vgoal, vstack1,vstack2,  vplayer, vselect_limit, vskaters, vcore, vjvalue, vsumjvalue, vteams) #vteams must be listed last


matrix_vector[is.na(matrix_vector)] <- 0
matrix_vector[is.infinite(matrix_vector)] <- 0

const.mat = matrix(matrix_vector, nrow = length(matrix_vector)/nrow(all_considerations), byrow = TRUE)
# 
# ## Define constraints and direction - 50000 salary
const.rhs = c(50000,    2,   3,   2,   1,    1,    1,    8-stack1size-stack2size,    11-stack1size-stack2size,    8,    stacks_in_core,    jvalue_min, min_sum_jvalue)
const.dir = c("<=" , ">=",">=",">=","==", "==", "==",                       "==",                        "==", "==",              ">=",          ">=", ">=")

for(t in 1:nrow(teams)){
  const.dir <- c(const.dir, "<=")
  const.rhs <- c(const.rhs, 5)
}


# 
# ### Optimize
objective.in <- all_considerations$build_proj
objective.in[is.nan(objective.in)] <- 0
objective.in[objective.in < 0] <- 0
optimum = lp(direction = "max", objective.in, const.mat, const.dir, const.rhs, all.bin = TRUE)
# 
all_considerations$optimal <- optimum$solution

lineup <- all_considerations %>%
  filter(optimal == 1)

if(nrow(lineup) > 0){

if(grepl("PP", lineup$Name[which(lineup$which_stack=="stack1")], fixed = TRUE)){
  lineup_stack1 <- stack1pp %>%
  filter(stackline == lineup$Name[which(lineup$which_stack=="stack1")]) %>%
  slice_max(order_by = build_proj, n = stack1size)
}else{
lineup_stack1 <- stack1 %>%
  filter(stackline == lineup$Name[which(lineup$which_stack=="stack1")]) %>%
  slice_max(order_by = build_proj, n = stack1size)

}
if(grepl("PP", lineup$Name[which(lineup$which_stack=="stack2")], fixed = TRUE)){
  lineup_stack2 <- stack2pp %>%
  filter(stackline == lineup$Name[which(lineup$which_stack=="stack2")]) %>%
  slice_max(order_by = build_proj, n = stack2size)
}else{

lineup_stack2 <- stack2 %>%
  filter(stackline == lineup$Name[which(lineup$which_stack=="stack2")]) %>%
  slice_max(order_by = build_proj, n = stack2size)
}
p_and_g <- lineup %>%
  filter(which_stack %in% c("player", "goalie"))

lineup_names <- c(lineup_stack1$Name, lineup_stack2$Name, p_and_g$Name)

lineup <- projections %>%
  filter(Name %in% lineup_names)

lineup <- mutate(lineup, order = case_when(
  Position == "C" ~ 1,
  Position == "W" ~ 2,
  Position == "D" ~ 3,
  Position == "G" ~ 4
))
lineup <- lineup[order(lineup$order, decreasing = FALSE),]
if(sum(lineup$Position=="C")>2 |sum(lineup$Position=="W")>3){
  lineup$order[3] <- 5
} else{
  lineup$order[6] <- 5
}
lineup <- lineup[order(lineup$order, decreasing = FALSE),]

export <- lineup$DKid

if(n==0){
  final_export <-export
  n <- 1
  
}else{
  final_export <- rbind(final_export, export)
  final_export <- unique(final_export)
  final_export <- final_export[complete.cases(final_export),]
  n <- nrow(final_export)
}
 setTxtProgressBar(pb, n)
}

}
close(pb)
colnames(final_export) <- c("C", "C", "W", "W", "W", "D", "D", "G", "UTIL")

ownership <- oprojections %>%
  select(Name, DKid, Team, Line, PP.Line.1)
ownership$ownership_pct <- 0

for(i in 1:length(ownership$Name)){
  ownership$ownership_pct[i] = sum(final_export == ownership$DKid[i])
}
ownership$ownership_pct <- ownership$ownership_pct/ num_lineups*100
ownership <- ownership[order(ownership$ownership_pct, decreasing = TRUE),]
View(ownership)

write.csv(final_export, "C:/Users/jorda/Downloads/DKLineupsNHL.csv", row.names = FALSE)

#test <- final_export[complete.cases(final_export),]
```

### Lineup Editor
```{r lineup-editor}

### Build lineups above, then use this to edit entries for direct upload

plineups <- read.csv("C:/Users/jorda/Downloads/DKEntriesNHL.csv")

plineups <- filter(plineups, !is.na(Entry.ID) & !is.na(as.numeric(Entry.ID))) %>%
  select(Entry.ID, Contest.Name, Contest.ID, Entry.Fee)

newlineups <- read.csv("C:/Users/jorda/Downloads/DKLineupsNHL.csv")

newlineups <- cbind(plineups, newlineups)
colnames(newlineups) <- c("Entry ID", "Contest Name", "Contest ID", "Entry Fee", "C", "C", "W", "W", "W", "D", "D", "G", "UTIL")

write.csv(newlineups, "C:/Users/jorda/Downloads/DKEntriesNHL.csv", row.names = FALSE)

```



### Historic results
```{r historic-results}

historic_results <- read.csv("C:/Users/jorda/Downloads/Historic Results - NHL.csv") %>%
  filter(!implied_win == "#N/A", !Actual == "#N/A") %>%
  mutate(implied_win = as.numeric(implied_win))

historic_results_goalies <- historic_results %>%
  filter(Position == "G", !Actual == 0)

historic_results_skaters <- historic_results %>%
  filter(!Position == "G", !Actual == 0)

hr_stacks <- historic_results_skaters[complete.cases(historic_results_skaters),] %>%
  group_by(Team, Line, DKLineProj) %>%
  summarise(Actual = sum(as.numeric(Actual)), Ownership = sum(as.numeric(Ownership)), implied_win = mean(implied_win), imp_p = sum(imp_p), imp_a = sum(imp_a), imp_bs = sum(imp_bs), imp_sog = sum(imp_sog), slate_games = mean(slate_games), DK.Implied.FPs = sum(DK.Implied.FPs))

lm_actuals <- lm(Actual ~  implied_win + DK.Implied.FPs + slate_games, data = historic_results_skaters)
summary(lm_actuals)
lm_owns <- lm(Ownership ~  implied_win + DK.Implied.FPs + slate_games, data = historic_results_skaters)
summary(lm_owns)

lm_actualg <- lm(Actual ~ implied_win +  DK.Implied.FPs + slate_games, data = historic_results_goalies)
summary(lm_actualg)
lm_owng <- lm(Ownership ~ implied_win + DK.Implied.FPs + slate_games, data = historic_results_goalies)
summary(lm_owng)

lm_actuals <- lm(Actual ~  implied_win + DK.Implied.FPs + slate_games, data = historic_results_skaters)
summary(lm_actuals)
lm_owns <- lm(Ownership ~  implied_win + DK.Implied.FPs + slate_games, data = historic_results_skaters)
summary(lm_owns)

lm_actualstack <- lm(Actual ~ DK.Implied.FPs , data = hr_stacks)
summary(lm_actualstack)
lm_ownstack <- lm(Ownership ~ implied_win + DK.Implied.FPs + slate_games, data = hr_stacks)
summary(lm_ownstack)

hr_stacks$projection <- predict(lm_actualstack, hr_stacks)
hr_stacks$proj_own <- predict(lm_ownstack, hr_stacks)

ggplot(hr_stacks) + 
  geom_point(aes(DK.Implied.FPs, Actual), color = "blue")+
  geom_point(aes(projection, Actual), color = "red")

ggplot(hr_stacks) +
  geom_point(aes(proj_own, Ownership), color = "green")
```
